Add extended aggregation
DataDog/datadogpy pull request #863
Opened 2024-10-28 17:27 UTC by andrewqian2001datadog

### Requirements for Contributing to this repository

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only fix one issue, or add one feature, at the time.
* The pull request must update the test suite to demonstrate the changed functionality.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see [CONTRIBUTING](/CONTRIBUTING.md). 

### What does this PR do?

### Description of the Change

### Alternate Designs

### Possible Drawbacks

### Verification Process

### Additional Notes

### Release Notes

### Review checklist (to be filled by reviewers)

- [ ] Feature or bug fix MUST have appropriate tests (unit, integration, etc...)
- [ ] PR title must be written as a CHANGELOG entry [(see why)](https://github.com/DataDog/datadogpy/blob/master/CONTRIBUTING.md#pull-request-title)
- [ ] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
- [ ] PR must have one `changelog/` label attached. If applicable it should have the `backward-incompatible` label attached.
- [ ] PR should not have `do-not-merge/` label attached.
- [ ] If Applicable, issue must have `kind/` and `severity/` labels attached at least.

2025-01-02 16:46 UTC, gh123man commented
Do we need to merge `master` into this branch? I think that may fix the failing tests.

2025-01-02 18:57 UTC, gh123man requested changes
Left some comments/questions.

In the go client, extended aggregation is behind a config flag, and disabled by default. 
I think we should do the same here. 

However first let's confirm the buffering behavior. I wonder if it would be simpler and have similar results if we enabled buffering and aggregation to work together (Or open question: Is the old buffering implementation still relevant if we keep this one instead?)

2025-01-02 18:57 UTC, gh123man commented on datadog/dogstatsd/buffered_metrics.py
> +    def __init__(self, name, tags, metric_type, specified_rate=1.0, max_metric_samples=0):
`max_metric_samples` appears to always be hardcoded to `0`. 
In the go client, I believe this is user configurable. Should we do the same in the python client?

2025-01-02 18:57 UTC, gh123man commented on datadog/dogstatsd/buffered_metrics.py
> +    def maybe_keep_sample(self, value):
[Also this comment thread is interesting](https://github.com/DataDog/datadog-go/pull/283/files#r1352035189) regarding how sampling interacts with aggregation/extended aggregation. I think we would want to ensure we match this behavior.

2025-01-02 18:57 UTC, gh123man commented on datadog/dogstatsd/base.py
> +        self._send = self._send_to_buffer
Why do we need to change the `_send` method when flushing aggregated metrics? 

The way I read this seems like we are buffering twice ex: histogram/distribution/timing in the buffered metric class, and then again by writing to the sender buffer via `_send_to_buffer`. 

Also - with aggregation enabled, `_start_flush_thread` is given the `flush_aggregated_metrics` method, so in this case will `flush_buffered_metrics` ever be called by the flush thread? 

Please correct me if I am wrong/misunderstanding.

2025-01-03 15:08 UTC, ddrthall commented on datadog/dogstatsd/aggregator.py
> +            with self._locks[metric_type]:
Nit: is this lock necessary? It looks like the buffered_metrics_map is more or less constant, with changes performed in submethods (like flush) that lock themselves

2025-01-03 15:09 UTC, ddrthall commented on datadog/dogstatsd/base.py
> +            self._report(m.name, m.metric_type, m.value, m.tags, m.rate, m.timestamp)
_report will perform its own sampling, so putting buffered metrics in post-sampling looks like it will cause them to be sampled twice

2025-01-15 17:54 UTC, ddrthall commented on datadog/dogstatsd/base.py
> +        :type max_metric_samples: integer
This param seems to be an older version of the per_context one, I don't think it's actually defined

2025-01-15 17:55 UTC, ddrthall commented on datadog/dogstatsd/base.py
> +        for m in sampled_metrics:
Nit: While this is definitely fully functional, I would be a bit more comfortable if _report was modified to allow the option to not internally sample. That way we only have one location to worry about changes to "are we disabled", "how do we handle constant tags", "how do we handle telemetry", etc.

2025-01-15 17:55 UTC, ddrthall commented on datadog/dogstatsd/max_sample_metric.py
> +        self.data = []
Likely makes sense to pre-allocate data in the case of non-zero max_metric_samples

2025-01-15 17:56 UTC, ddrthall commented on datadog/dogstatsd/max_sample_metric.py
> +        if self.max_metric_samples > 0:
All or most of this function will need lock protections, a number of internal variables like stored metrics and the data array are potentially being updated by multiple threads.

2025-01-15 17:57 UTC, ddrthall commented on datadog/dogstatsd/max_sample_metric.py
> +                i = random.randint(0, self.total_metric_samples - 1)
This looks like an off-by-one - if max_metric_samples is five, then the sixth sample should have a chance to not be persisted to the data array. It looks like we're persisting it 100% of the time here.

2025-01-15 17:58 UTC, ddrthall commented on datadog/dogstatsd/max_sample_metric.py
> +            rate = self.stored_metric_samples / total_metric_samples
With the current structure it is highly likely that we can always use this value, pending confirmation that we can safely increment all skips behind a lock without too heavy a performance hit.

2025-01-15 17:59 UTC, ddrthall commented on datadog/dogstatsd/max_sample_metric_context.py
> +            copiedValues = self.values.copy()
It doesn't look to me like the copy and the clear are necessary - the subsequent assignment of values to an empty dict should be generally equivalent to the clear for our use case, and without a clear call there's no need to shallow copy the dict.

2025-01-15 17:59 UTC, ddrthall commented on datadog/dogstatsd/max_sample_metric_context.py
> +        self.nb_context += len(copiedValues)
nb_context doesn't seem to be used

2025-01-15 18:00 UTC, ddrthall commented on datadog/dogstatsd/max_sample_metric_context.py
> +        if keeping_sample:
It looks like we're likely racing the flush to persist this correctly. Operating flow: 
Thread in sample pulls a metric from the values dict and gets pre-empted after dropping the metric_context's lock. 
Separate thread enters flush, pulls the metric from values and removes further reference to it, then flushes the metric.
Original thread wakes back up and continues operating on the metric object that it had pulled, unaware that the metric had already been flushed and any additional samples added will be ignored.

2025-01-24 14:15 UTC, ddrthall commented on datadog/dogstatsd/max_sample_metric.py
> +                values[i] = MetricAggregator(self.name, self.tags, self.specified_rate, self.metric_type, self.data[i])
I fairly confident that we want the `rate = self.stored_metric_samples / total_metric_samples` value here, since that is the actual real rate. Specified rate is used in the go variant as a workaround to not reliably being able to determine the real rate (go code has issues guaranteeing updates to its own version of total_metric_samples)

2025-01-24 14:16 UTC, ddrthall commented on datadog/dogstatsd/max_sample_metric.py
> +            values = [None] * self.stored_metric_samples
Nit: Python list comprehension, e.g. some_list = [ x for i in y], is actually faster than a pre-allocate, which itself is faster than an empty initialization and append loop. I would be rather surprised if any of the variants actually have a performance impact for a flush operation, but wanted to let you know that what you originally had here was actually optimal.

2025-01-24 14:16 UTC, ddrthall commented on datadog/dogstatsd/max_sample_metric.py
> +        if self.max_metric_samples > 0:
Updated functionality looks safe to me.
Addendum nit: since this method requires a lock but relies on the caller to actually utilize said lock, it is common practice to append the work unsafe to the method name.

2025-01-24 14:16 UTC, ddrthall commented on datadog/dogstatsd/base.py
> +            print("Aggregated histogram")
Reminder to remove the prints here and below

2025-01-24 16:09 UTC, ddrthall approved these changes

2025-01-24 19:02 UTC, ddrthall approved these changes

2025-01-27 18:32 UTC, skarimo approved these changes

2025-01-27 20:36 UTC, gh123man approved these changes

2025-01-27 20:37 UTC, merged